/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package views;

import java.net.Inet4Address;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.SocketException;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JProgressBar;
import personalhealthtracker.ActivityReceiver;

/**
 *
 * @author Gennaro
 */
public class ActivityReceiverView extends javax.swing.JPanel
{

    /**
     * Creates new form ActivityReceiverView
     */
    public ActivityReceiverView()
    {
        initComponents();
        InetAddress address = getAddress();
        String ipAddress = address == null ? "ERROR" : address.getHostAddress();
        ipAddressLabel.setText(ipAddress);
        
        instructionTextArea.setEditable(false);
        instructionTextArea.setLineWrap(true);
        instructionTextArea.setWrapStyleWord(true);
        instructionTextArea.setText("To receive activites from your phone's Personal Health Tracker app, "
                + "input the IP Address into the text box in your device's application. "
                + "After confirming the IP Address, your data will be shared with this computer. If your IP Address "
                + "displays as \"ERROR\", you are not connected to an appropriate network. Please confirm "
                + "that your mobile device is connected to the same network as your computer before attempting to connect.");
    }
    
    // Get the user's IP Address. This method skips over any callback addresses such as 127.0.0.1.
    private static InetAddress getAddress() {
        try
        {
            InetAddress toReturn = null;
            
            Enumeration<NetworkInterface> en = NetworkInterface.getNetworkInterfaces();
            
            loop:
            while(en.hasMoreElements()) {
                NetworkInterface i = en.nextElement();
                for(Enumeration<InetAddress> en2 = i.getInetAddresses(); en2.hasMoreElements();) {
                    InetAddress addr = en2.nextElement();
                    if(addr.isLoopbackAddress()) {
                        continue;
                    }
                    if(addr instanceof Inet4Address) {
                        toReturn = addr;
                        break loop;
                    }
                }
            }
            return toReturn;
        }
        catch (SocketException ex)
        {
            Logger.getLogger(ActivityReceiver.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return null;
    }
    
    public JProgressBar getProgressBar()
    {
        return progressBar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        ipAddressLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        instructionTextArea = new javax.swing.JTextArea();

        jLabel1.setText("IP Address:");

        ipAddressLabel.setText("jLabel2");

        instructionTextArea.setColumns(20);
        instructionTextArea.setRows(5);
        jScrollPane1.setViewportView(instructionTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ipAddressLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 48, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ipAddressLabel))
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea instructionTextArea;
    private javax.swing.JLabel ipAddressLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
